name: Scheduled Draft Publisher

on:
  schedule:
    - cron: "0 9 * * *"  # 09:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install gray-matter if it's not already in your package.json
      - name: Install dependencies needed by scripts
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi
          npm i gray-matter

      - name: Sanitize drafts (remove affiliate content)
        run: node scripts/sanitize-markdown.js drafts

      - name: Publish one draft → posts (force valid date)
        run: node scripts/publish-draft.js

      - name: (Optional) Sanitize posts too
        run: node scripts/sanitize-markdown.js posts

      - name: Commit & push changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto-publish: sanitize + publish (date normalized)"
            git push
          else
            echo "No changes to commit."
          fi
